//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.24 at 02:38:28 PM PDT 
//


package sandbox.liquibase.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}addForeignKeyConstraintAttrib"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "addForeignKeyConstraint")
public class AddForeignKeyConstraint {

    @XmlAttribute
    protected String baseTableSchemaName;
    @XmlAttribute(required = true)
    protected String baseTableName;
    @XmlAttribute(required = true)
    protected String baseColumnNames;
    @XmlAttribute
    protected String constraintName;
    @XmlAttribute
    protected String referencedTableSchemaName;
    @XmlAttribute(required = true)
    protected String referencedTableName;
    @XmlAttribute(required = true)
    protected String referencedColumnNames;
    @XmlAttribute
    protected Boolean deferrable;
    @XmlAttribute
    protected Boolean initiallyDeferred;
    @XmlAttribute
    protected Boolean deleteCascade;
    @XmlAttribute
    protected String onDelete;
    @XmlAttribute
    protected String onUpdate;

    /**
     * Gets the value of the baseTableSchemaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseTableSchemaName() {
        return baseTableSchemaName;
    }

    /**
     * Sets the value of the baseTableSchemaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseTableSchemaName(String value) {
        this.baseTableSchemaName = value;
    }

    /**
     * Gets the value of the baseTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseTableName() {
        return baseTableName;
    }

    /**
     * Sets the value of the baseTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseTableName(String value) {
        this.baseTableName = value;
    }

    /**
     * Gets the value of the baseColumnNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseColumnNames() {
        return baseColumnNames;
    }

    /**
     * Sets the value of the baseColumnNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseColumnNames(String value) {
        this.baseColumnNames = value;
    }

    /**
     * Gets the value of the constraintName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstraintName() {
        return constraintName;
    }

    /**
     * Sets the value of the constraintName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstraintName(String value) {
        this.constraintName = value;
    }

    /**
     * Gets the value of the referencedTableSchemaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedTableSchemaName() {
        return referencedTableSchemaName;
    }

    /**
     * Sets the value of the referencedTableSchemaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedTableSchemaName(String value) {
        this.referencedTableSchemaName = value;
    }

    /**
     * Gets the value of the referencedTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedTableName() {
        return referencedTableName;
    }

    /**
     * Sets the value of the referencedTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedTableName(String value) {
        this.referencedTableName = value;
    }

    /**
     * Gets the value of the referencedColumnNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedColumnNames() {
        return referencedColumnNames;
    }

    /**
     * Sets the value of the referencedColumnNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedColumnNames(String value) {
        this.referencedColumnNames = value;
    }

    /**
     * Gets the value of the deferrable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeferrable() {
        return deferrable;
    }

    /**
     * Sets the value of the deferrable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeferrable(Boolean value) {
        this.deferrable = value;
    }

    /**
     * Gets the value of the initiallyDeferred property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInitiallyDeferred() {
        return initiallyDeferred;
    }

    /**
     * Sets the value of the initiallyDeferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInitiallyDeferred(Boolean value) {
        this.initiallyDeferred = value;
    }

    /**
     * Gets the value of the deleteCascade property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeleteCascade() {
        return deleteCascade;
    }

    /**
     * Sets the value of the deleteCascade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeleteCascade(Boolean value) {
        this.deleteCascade = value;
    }

    /**
     * Gets the value of the onDelete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnDelete() {
        return onDelete;
    }

    /**
     * Sets the value of the onDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnDelete(String value) {
        this.onDelete = value;
    }

    /**
     * Gets the value of the onUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnUpdate() {
        return onUpdate;
    }

    /**
     * Sets the value of the onUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnUpdate(String value) {
        this.onUpdate = value;
    }

}
