//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.24 at 02:38:28 PM PDT 
//


package sandbox.liquibase.xml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="preConditions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}PreConditionChildren" maxOccurs="unbounded"/>
 *                 &lt;/choice>
 *                 &lt;attribute name="onFail" type="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}onChangeLogPreconditionErrorOrFail" />
 *                 &lt;attribute name="onError" type="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}onChangeLogPreconditionErrorOrFail" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="property" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="changeSet" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="validCheckSum" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}comment" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="preConditions" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;choice>
 *                               &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}PreConditionChildren" maxOccurs="unbounded"/>
 *                             &lt;/choice>
 *                             &lt;attribute name="onFail" type="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}onChangeSetPreconditionErrorOrFail" />
 *                             &lt;attribute name="onError" type="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}onChangeSetPreconditionErrorOrFail" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;choice>
 *                       &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}tagDatabase"/>
 *                       &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}changeSetChildren" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;/choice>
 *                     &lt;element name="modifySql" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;choice>
 *                               &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}modifySqlChildren" maxOccurs="unbounded"/>
 *                             &lt;/choice>
 *                             &lt;attribute name="dbms" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;attGroup ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}changeSetAttributes"/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="include" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="relativeToChangelogFile" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="includeAll" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}changeLogAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "preConditions",
    "property",
    "changeSetOrIncludeOrIncludeAll"
})
@XmlRootElement(name = "databaseChangeLog")
public class DatabaseChangeLog {

    protected DatabaseChangeLog.PreConditions preConditions;
    protected List<DatabaseChangeLog.Property> property;
    @XmlElements({
        @XmlElement(name = "changeSet", type = DatabaseChangeLog.ChangeSet.class),
        @XmlElement(name = "include", type = DatabaseChangeLog.Include.class),
        @XmlElement(name = "includeAll", type = DatabaseChangeLog.IncludeAll.class)
    })
    protected List<Object> changeSetOrIncludeOrIncludeAll;
    @XmlAttribute
    protected String logicalFilePath;

    /**
     * Gets the value of the preConditions property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseChangeLog.PreConditions }
     *     
     */
    public DatabaseChangeLog.PreConditions getPreConditions() {
        return preConditions;
    }

    /**
     * Sets the value of the preConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseChangeLog.PreConditions }
     *     
     */
    public void setPreConditions(DatabaseChangeLog.PreConditions value) {
        this.preConditions = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatabaseChangeLog.Property }
     * 
     * 
     */
    public List<DatabaseChangeLog.Property> getProperty() {
        if (property == null) {
            property = new ArrayList<DatabaseChangeLog.Property>();
        }
        return this.property;
    }

    /**
     * Gets the value of the changeSetOrIncludeOrIncludeAll property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changeSetOrIncludeOrIncludeAll property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChangeSetOrIncludeOrIncludeAll().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatabaseChangeLog.ChangeSet }
     * {@link DatabaseChangeLog.Include }
     * {@link DatabaseChangeLog.IncludeAll }
     * 
     * 
     */
    public List<Object> getChangeSetOrIncludeOrIncludeAll() {
        if (changeSetOrIncludeOrIncludeAll == null) {
            changeSetOrIncludeOrIncludeAll = new ArrayList<Object>();
        }
        return this.changeSetOrIncludeOrIncludeAll;
    }

    /**
     * Gets the value of the logicalFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalFilePath() {
        return logicalFilePath;
    }

    /**
     * Sets the value of the logicalFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalFilePath(String value) {
        this.logicalFilePath = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="validCheckSum" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}comment" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="preConditions" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}PreConditionChildren" maxOccurs="unbounded"/>
     *                 &lt;/choice>
     *                 &lt;attribute name="onFail" type="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}onChangeSetPreconditionErrorOrFail" />
     *                 &lt;attribute name="onError" type="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}onChangeSetPreconditionErrorOrFail" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;choice>
     *           &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}tagDatabase"/>
     *           &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}changeSetChildren" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;/choice>
     *         &lt;element name="modifySql" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}modifySqlChildren" maxOccurs="unbounded"/>
     *                 &lt;/choice>
     *                 &lt;attribute name="dbms" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}changeSetAttributes"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "validCheckSum",
        "preConditions",
        "tagDatabase",
        "changeSetChildren",
        "modifySql"
    })
    public static class ChangeSet {

        protected List<DatabaseChangeLog.ChangeSet.ValidCheckSum> validCheckSum;
        protected DatabaseChangeLog.ChangeSet.PreConditions preConditions;
        protected TagDatabase tagDatabase;
        @XmlElements({
            @XmlElement(name = "addLookupTable", type = AddLookupTable.class),
            @XmlElement(name = "sql", type = Sql.class),
            @XmlElement(name = "dropDefaultValue", type = DropDefaultValue.class),
            @XmlElement(name = "dropPrimaryKey", type = DropPrimaryKey.class),
            @XmlElement(name = "dropColumn", type = DropColumn.class),
            @XmlElement(name = "dropAllForeignKeyConstraints", type = DropAllForeignKeyConstraints.class),
            @XmlElement(name = "renameColumn", type = RenameColumn.class),
            @XmlElement(name = "renameTable", type = RenameTable.class),
            @XmlElement(name = "modifyColumn", type = ModifyColumn.class),
            @XmlElement(name = "executeCommand", type = ExecuteCommand.class),
            @XmlElement(name = "sqlFile", type = SqlFile.class),
            @XmlElement(name = "dropForeignKeyConstraint", type = DropForeignKeyConstraint.class),
            @XmlElement(name = "loadData", type = LoadData.class),
            @XmlElement(name = "insert", type = Insert.class),
            @XmlElement(name = "delete", type = Delete.class),
            @XmlElement(name = "update", type = Update.class),
            @XmlElement(name = "addUniqueConstraint", type = AddUniqueConstraint.class),
            @XmlElement(name = "stop", type = Stop.class),
            @XmlElement(name = "createTable", type = CreateTable.class),
            @XmlElement(name = "createView", type = CreateView.class),
            @XmlElement(name = "addNotNullConstraint", type = AddNotNullConstraint.class),
            @XmlElement(name = "addDefaultValue", type = AddDefaultValue.class),
            @XmlElement(name = "dropSequence", type = DropSequence.class),
            @XmlElement(name = "addAutoIncrement", type = AddAutoIncrement.class),
            @XmlElement(name = "rollback", type = Rollback.class),
            @XmlElement(name = "addPrimaryKey", type = AddPrimaryKey.class),
            @XmlElement(name = "renameView", type = RenameView.class),
            @XmlElement(name = "createProcedure", type = CreateProcedure.class),
            @XmlElement(name = "createIndex", type = CreateIndex.class),
            @XmlElement(name = "comment", type = String.class),
            @XmlElement(name = "addColumn", type = AddColumn.class),
            @XmlElement(name = "alterSequence", type = AlterSequence.class),
            @XmlElement(name = "addForeignKeyConstraint", type = AddForeignKeyConstraint.class),
            @XmlElement(name = "mergeColumns", type = MergeColumns.class),
            @XmlElement(name = "customChange", type = CustomChange.class),
            @XmlElement(name = "dropIndex", type = DropIndex.class),
            @XmlElement(name = "dropTable", type = DropTable.class),
            @XmlElement(name = "dropUniqueConstraint", type = DropUniqueConstraint.class),
            @XmlElement(name = "createSequence", type = CreateSequence.class),
            @XmlElement(name = "dropView", type = DropView.class),
            @XmlElement(name = "dropNotNullConstraint", type = DropNotNullConstraint.class)
        })
        protected List<Object> changeSetChildren;
        protected List<DatabaseChangeLog.ChangeSet.ModifySql> modifySql;
        @XmlAttribute(required = true)
        protected String id;
        @XmlAttribute(required = true)
        protected String author;
        @XmlAttribute
        protected String context;
        @XmlAttribute
        protected String dbms;
        @XmlAttribute
        protected Boolean runOnChange;
        @XmlAttribute
        protected Boolean runAlways;
        @XmlAttribute
        protected Boolean failOnError;
        @XmlAttribute
        protected Boolean runInTransaction;

        /**
         * Gets the value of the validCheckSum property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the validCheckSum property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValidCheckSum().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DatabaseChangeLog.ChangeSet.ValidCheckSum }
         * 
         * 
         */
        public List<DatabaseChangeLog.ChangeSet.ValidCheckSum> getValidCheckSum() {
            if (validCheckSum == null) {
                validCheckSum = new ArrayList<DatabaseChangeLog.ChangeSet.ValidCheckSum>();
            }
            return this.validCheckSum;
        }

        /**
         * Gets the value of the preConditions property.
         * 
         * @return
         *     possible object is
         *     {@link DatabaseChangeLog.ChangeSet.PreConditions }
         *     
         */
        public DatabaseChangeLog.ChangeSet.PreConditions getPreConditions() {
            return preConditions;
        }

        /**
         * Sets the value of the preConditions property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatabaseChangeLog.ChangeSet.PreConditions }
         *     
         */
        public void setPreConditions(DatabaseChangeLog.ChangeSet.PreConditions value) {
            this.preConditions = value;
        }

        /**
         * Gets the value of the tagDatabase property.
         * 
         * @return
         *     possible object is
         *     {@link TagDatabase }
         *     
         */
        public TagDatabase getTagDatabase() {
            return tagDatabase;
        }

        /**
         * Sets the value of the tagDatabase property.
         * 
         * @param value
         *     allowed object is
         *     {@link TagDatabase }
         *     
         */
        public void setTagDatabase(TagDatabase value) {
            this.tagDatabase = value;
        }

        /**
         * Gets the value of the changeSetChildren property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the changeSetChildren property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChangeSetChildren().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AddLookupTable }
         * {@link Sql }
         * {@link DropDefaultValue }
         * {@link DropPrimaryKey }
         * {@link DropColumn }
         * {@link DropAllForeignKeyConstraints }
         * {@link RenameColumn }
         * {@link RenameTable }
         * {@link ModifyColumn }
         * {@link ExecuteCommand }
         * {@link SqlFile }
         * {@link DropForeignKeyConstraint }
         * {@link LoadData }
         * {@link Insert }
         * {@link Delete }
         * {@link Update }
         * {@link AddUniqueConstraint }
         * {@link Stop }
         * {@link CreateTable }
         * {@link CreateView }
         * {@link AddNotNullConstraint }
         * {@link AddDefaultValue }
         * {@link DropSequence }
         * {@link AddAutoIncrement }
         * {@link Rollback }
         * {@link AddPrimaryKey }
         * {@link RenameView }
         * {@link CreateProcedure }
         * {@link CreateIndex }
         * {@link String }
         * {@link AddColumn }
         * {@link AlterSequence }
         * {@link AddForeignKeyConstraint }
         * {@link MergeColumns }
         * {@link CustomChange }
         * {@link DropIndex }
         * {@link DropTable }
         * {@link DropUniqueConstraint }
         * {@link CreateSequence }
         * {@link DropView }
         * {@link DropNotNullConstraint }
         * 
         * 
         */
        public List<Object> getChangeSetChildren() {
            if (changeSetChildren == null) {
                changeSetChildren = new ArrayList<Object>();
            }
            return this.changeSetChildren;
        }

        /**
         * Gets the value of the modifySql property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the modifySql property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getModifySql().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DatabaseChangeLog.ChangeSet.ModifySql }
         * 
         * 
         */
        public List<DatabaseChangeLog.ChangeSet.ModifySql> getModifySql() {
            if (modifySql == null) {
                modifySql = new ArrayList<DatabaseChangeLog.ChangeSet.ModifySql>();
            }
            return this.modifySql;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthor(String value) {
            this.author = value;
        }

        /**
         * Gets the value of the context property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContext() {
            return context;
        }

        /**
         * Sets the value of the context property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContext(String value) {
            this.context = value;
        }

        /**
         * Gets the value of the dbms property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDbms() {
            return dbms;
        }

        /**
         * Sets the value of the dbms property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDbms(String value) {
            this.dbms = value;
        }

        /**
         * Gets the value of the runOnChange property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isRunOnChange() {
            return runOnChange;
        }

        /**
         * Sets the value of the runOnChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setRunOnChange(Boolean value) {
            this.runOnChange = value;
        }

        /**
         * Gets the value of the runAlways property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isRunAlways() {
            return runAlways;
        }

        /**
         * Sets the value of the runAlways property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setRunAlways(Boolean value) {
            this.runAlways = value;
        }

        /**
         * Gets the value of the failOnError property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isFailOnError() {
            return failOnError;
        }

        /**
         * Sets the value of the failOnError property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setFailOnError(Boolean value) {
            this.failOnError = value;
        }

        /**
         * Gets the value of the runInTransaction property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isRunInTransaction() {
            if (runInTransaction == null) {
                return true;
            } else {
                return runInTransaction;
            }
        }

        /**
         * Sets the value of the runInTransaction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setRunInTransaction(Boolean value) {
            this.runInTransaction = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}modifySqlChildren" maxOccurs="unbounded"/>
         *       &lt;/choice>
         *       &lt;attribute name="dbms" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "modifySqlChildren"
        })
        public static class ModifySql {

            @XmlElements({
                @XmlElement(name = "regExpReplace", type = DatabaseChangeLog.ChangeSet.ModifySql.RegExpReplace.class),
                @XmlElement(name = "replace", type = DatabaseChangeLog.ChangeSet.ModifySql.Replace.class),
                @XmlElement(name = "prepend", type = DatabaseChangeLog.ChangeSet.ModifySql.Prepend.class),
                @XmlElement(name = "append", type = DatabaseChangeLog.ChangeSet.ModifySql.Append.class)
            })
            protected List<Object> modifySqlChildren;
            @XmlAttribute
            protected String dbms;

            /**
             * Gets the value of the modifySqlChildren property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the modifySqlChildren property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getModifySqlChildren().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DatabaseChangeLog.ChangeSet.ModifySql.RegExpReplace }
             * {@link DatabaseChangeLog.ChangeSet.ModifySql.Replace }
             * {@link DatabaseChangeLog.ChangeSet.ModifySql.Prepend }
             * {@link DatabaseChangeLog.ChangeSet.ModifySql.Append }
             * 
             * 
             */
            public List<Object> getModifySqlChildren() {
                if (modifySqlChildren == null) {
                    modifySqlChildren = new ArrayList<Object>();
                }
                return this.modifySqlChildren;
            }

            /**
             * Gets the value of the dbms property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDbms() {
                return dbms;
            }

            /**
             * Sets the value of the dbms property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDbms(String value) {
                this.dbms = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Append {

                @XmlAttribute(required = true)
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Prepend {

                @XmlAttribute(required = true)
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="replace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="with" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class RegExpReplace {

                @XmlAttribute(required = true)
                protected String replace;
                @XmlAttribute(required = true)
                protected String with;

                /**
                 * Gets the value of the replace property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReplace() {
                    return replace;
                }

                /**
                 * Sets the value of the replace property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReplace(String value) {
                    this.replace = value;
                }

                /**
                 * Gets the value of the with property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWith() {
                    return with;
                }

                /**
                 * Sets the value of the with property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWith(String value) {
                    this.with = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="replace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="with" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Replace {

                @XmlAttribute(required = true)
                protected String replace;
                @XmlAttribute(required = true)
                protected String with;

                /**
                 * Gets the value of the replace property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReplace() {
                    return replace;
                }

                /**
                 * Sets the value of the replace property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReplace(String value) {
                    this.replace = value;
                }

                /**
                 * Gets the value of the with property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWith() {
                    return with;
                }

                /**
                 * Sets the value of the with property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWith(String value) {
                    this.with = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}PreConditionChildren" maxOccurs="unbounded"/>
         *       &lt;/choice>
         *       &lt;attribute name="onFail" type="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}onChangeSetPreconditionErrorOrFail" />
         *       &lt;attribute name="onError" type="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}onChangeSetPreconditionErrorOrFail" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "preConditionChildren"
        })
        public static class PreConditions {

            @XmlElements({
                @XmlElement(name = "customPrecondition", type = CustomPrecondition.class),
                @XmlElement(name = "or", type = Or.class),
                @XmlElement(name = "runningAs", type = RunningAs.class),
                @XmlElement(name = "primaryKeyExists", type = PrimaryKeyExists.class),
                @XmlElement(name = "tableExists", type = TableExists.class),
                @XmlElement(name = "sqlCheck", type = SqlCheck.class),
                @XmlElement(name = "viewExists", type = ViewExists.class),
                @XmlElement(name = "and", type = And.class),
                @XmlElement(name = "sequenceExists", type = SequenceExists.class),
                @XmlElement(name = "indexExists", type = IndexExists.class),
                @XmlElement(name = "foreignKeyConstraintExists", type = ForeignKeyConstraintExists.class),
                @XmlElement(name = "dbms", type = Dbms.class),
                @XmlElement(name = "not", type = Not.class),
                @XmlElement(name = "columnExists", type = ColumnExists.class),
                @XmlElement(name = "changeSetExecuted", type = ChangeSetExecuted.class)
            })
            protected List<Object> preConditionChildren;
            @XmlAttribute
            protected OnChangeSetPreconditionErrorOrFail onFail;
            @XmlAttribute
            protected OnChangeSetPreconditionErrorOrFail onError;

            /**
             * Gets the value of the preConditionChildren property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the preConditionChildren property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPreConditionChildren().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CustomPrecondition }
             * {@link Or }
             * {@link RunningAs }
             * {@link PrimaryKeyExists }
             * {@link TableExists }
             * {@link SqlCheck }
             * {@link ViewExists }
             * {@link And }
             * {@link SequenceExists }
             * {@link IndexExists }
             * {@link ForeignKeyConstraintExists }
             * {@link Dbms }
             * {@link Not }
             * {@link ColumnExists }
             * {@link ChangeSetExecuted }
             * 
             * 
             */
            public List<Object> getPreConditionChildren() {
                if (preConditionChildren == null) {
                    preConditionChildren = new ArrayList<Object>();
                }
                return this.preConditionChildren;
            }

            /**
             * Gets the value of the onFail property.
             * 
             * @return
             *     possible object is
             *     {@link OnChangeSetPreconditionErrorOrFail }
             *     
             */
            public OnChangeSetPreconditionErrorOrFail getOnFail() {
                return onFail;
            }

            /**
             * Sets the value of the onFail property.
             * 
             * @param value
             *     allowed object is
             *     {@link OnChangeSetPreconditionErrorOrFail }
             *     
             */
            public void setOnFail(OnChangeSetPreconditionErrorOrFail value) {
                this.onFail = value;
            }

            /**
             * Gets the value of the onError property.
             * 
             * @return
             *     possible object is
             *     {@link OnChangeSetPreconditionErrorOrFail }
             *     
             */
            public OnChangeSetPreconditionErrorOrFail getOnError() {
                return onError;
            }

            /**
             * Sets the value of the onError property.
             * 
             * @param value
             *     allowed object is
             *     {@link OnChangeSetPreconditionErrorOrFail }
             *     
             */
            public void setOnError(OnChangeSetPreconditionErrorOrFail value) {
                this.onError = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}comment" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class ValidCheckSum {

            @XmlElementRef(name = "comment", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = JAXBElement.class)
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link String }
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="relativeToChangelogFile" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Include {

        @XmlAttribute(required = true)
        protected String file;
        @XmlAttribute
        protected Boolean relativeToChangelogFile;

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }

        /**
         * Gets the value of the relativeToChangelogFile property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isRelativeToChangelogFile() {
            return relativeToChangelogFile;
        }

        /**
         * Sets the value of the relativeToChangelogFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setRelativeToChangelogFile(Boolean value) {
            this.relativeToChangelogFile = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IncludeAll {

        @XmlAttribute(required = true)
        protected String path;

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}PreConditionChildren" maxOccurs="unbounded"/>
     *       &lt;/choice>
     *       &lt;attribute name="onFail" type="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}onChangeLogPreconditionErrorOrFail" />
     *       &lt;attribute name="onError" type="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}onChangeLogPreconditionErrorOrFail" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "preConditionChildren"
    })
    public static class PreConditions {

        @XmlElements({
            @XmlElement(name = "customPrecondition", type = CustomPrecondition.class),
            @XmlElement(name = "changeSetExecuted", type = ChangeSetExecuted.class),
            @XmlElement(name = "sequenceExists", type = SequenceExists.class),
            @XmlElement(name = "dbms", type = Dbms.class),
            @XmlElement(name = "tableExists", type = TableExists.class),
            @XmlElement(name = "columnExists", type = ColumnExists.class),
            @XmlElement(name = "indexExists", type = IndexExists.class),
            @XmlElement(name = "sqlCheck", type = SqlCheck.class),
            @XmlElement(name = "and", type = And.class),
            @XmlElement(name = "or", type = Or.class),
            @XmlElement(name = "primaryKeyExists", type = PrimaryKeyExists.class),
            @XmlElement(name = "runningAs", type = RunningAs.class),
            @XmlElement(name = "not", type = Not.class),
            @XmlElement(name = "viewExists", type = ViewExists.class),
            @XmlElement(name = "foreignKeyConstraintExists", type = ForeignKeyConstraintExists.class)
        })
        protected List<Object> preConditionChildren;
        @XmlAttribute
        protected OnChangeLogPreconditionErrorOrFail onFail;
        @XmlAttribute
        protected OnChangeLogPreconditionErrorOrFail onError;

        /**
         * Gets the value of the preConditionChildren property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the preConditionChildren property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPreConditionChildren().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CustomPrecondition }
         * {@link ChangeSetExecuted }
         * {@link SequenceExists }
         * {@link Dbms }
         * {@link TableExists }
         * {@link ColumnExists }
         * {@link IndexExists }
         * {@link SqlCheck }
         * {@link And }
         * {@link Or }
         * {@link PrimaryKeyExists }
         * {@link RunningAs }
         * {@link Not }
         * {@link ViewExists }
         * {@link ForeignKeyConstraintExists }
         * 
         * 
         */
        public List<Object> getPreConditionChildren() {
            if (preConditionChildren == null) {
                preConditionChildren = new ArrayList<Object>();
            }
            return this.preConditionChildren;
        }

        /**
         * Gets the value of the onFail property.
         * 
         * @return
         *     possible object is
         *     {@link OnChangeLogPreconditionErrorOrFail }
         *     
         */
        public OnChangeLogPreconditionErrorOrFail getOnFail() {
            return onFail;
        }

        /**
         * Sets the value of the onFail property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnChangeLogPreconditionErrorOrFail }
         *     
         */
        public void setOnFail(OnChangeLogPreconditionErrorOrFail value) {
            this.onFail = value;
        }

        /**
         * Gets the value of the onError property.
         * 
         * @return
         *     possible object is
         *     {@link OnChangeLogPreconditionErrorOrFail }
         *     
         */
        public OnChangeLogPreconditionErrorOrFail getOnError() {
            return onError;
        }

        /**
         * Sets the value of the onError property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnChangeLogPreconditionErrorOrFail }
         *     
         */
        public void setOnError(OnChangeLogPreconditionErrorOrFail value) {
            this.onError = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Property {

        @XmlAttribute
        protected String file;
        @XmlAttribute
        protected String name;
        @XmlAttribute
        protected String value;

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
