//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.24 at 02:38:28 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
//@javax.xml.bind.annotation.XmlSchema(
//		namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", 
//		location="http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-1.9.xsd",
//		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
//		)
//@javax.xml.bind.annotation.XmlSchema(
//		namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", 
//		location="http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-1.9.xsd",
//		xmlns={@XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance")},
//		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
//		)
package sandbox.liquibase.xml;
import javax.xml.bind.annotation.XmlNs;

