//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.24 at 02:38:28 PM PDT 
//


package sandbox.liquibase.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;group ref="{http://www.liquibase.org/xml/ns/dbchangelog/1.9}changeSetChildren" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="changeSetPath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="changeSetAuthor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="changeSetId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "rollback")
public class Rollback {

    @XmlElementRefs({
        @XmlElementRef(name = "update", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = Update.class),
        @XmlElementRef(name = "addNotNullConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = AddNotNullConstraint.class),
        @XmlElementRef(name = "addAutoIncrement", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = AddAutoIncrement.class),
        @XmlElementRef(name = "addForeignKeyConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = AddForeignKeyConstraint.class),
        @XmlElementRef(name = "delete", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = Delete.class),
        @XmlElementRef(name = "stop", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = Stop.class),
        @XmlElementRef(name = "dropPrimaryKey", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropPrimaryKey.class),
        @XmlElementRef(name = "createProcedure", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = CreateProcedure.class),
        @XmlElementRef(name = "modifyColumn", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = ModifyColumn.class),
        @XmlElementRef(name = "dropForeignKeyConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropForeignKeyConstraint.class),
        @XmlElementRef(name = "dropColumn", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropColumn.class),
        @XmlElementRef(name = "rollback", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = Rollback.class),
        @XmlElementRef(name = "alterSequence", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = AlterSequence.class),
        @XmlElementRef(name = "renameView", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = RenameView.class),
        @XmlElementRef(name = "loadData", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = LoadData.class),
        @XmlElementRef(name = "dropUniqueConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropUniqueConstraint.class),
        @XmlElementRef(name = "dropSequence", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropSequence.class),
        @XmlElementRef(name = "addColumn", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = AddColumn.class),
        @XmlElementRef(name = "renameTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = RenameTable.class),
        @XmlElementRef(name = "mergeColumns", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = MergeColumns.class),
        @XmlElementRef(name = "dropNotNullConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropNotNullConstraint.class),
        @XmlElementRef(name = "comment", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = JAXBElement.class),
        @XmlElementRef(name = "createTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = CreateTable.class),
        @XmlElementRef(name = "dropDefaultValue", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropDefaultValue.class),
        @XmlElementRef(name = "renameColumn", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = RenameColumn.class),
        @XmlElementRef(name = "addDefaultValue", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = AddDefaultValue.class),
        @XmlElementRef(name = "dropTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropTable.class),
        @XmlElementRef(name = "customChange", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = CustomChange.class),
        @XmlElementRef(name = "addUniqueConstraint", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = AddUniqueConstraint.class),
        @XmlElementRef(name = "dropAllForeignKeyConstraints", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropAllForeignKeyConstraints.class),
        @XmlElementRef(name = "addLookupTable", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = AddLookupTable.class),
        @XmlElementRef(name = "createSequence", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = CreateSequence.class),
        @XmlElementRef(name = "executeCommand", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = ExecuteCommand.class),
        @XmlElementRef(name = "sql", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = Sql.class),
        @XmlElementRef(name = "insert", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = Insert.class),
        @XmlElementRef(name = "createView", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = CreateView.class),
        @XmlElementRef(name = "createIndex", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = CreateIndex.class),
        @XmlElementRef(name = "addPrimaryKey", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = AddPrimaryKey.class),
        @XmlElementRef(name = "dropIndex", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropIndex.class),
        @XmlElementRef(name = "sqlFile", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = SqlFile.class),
        @XmlElementRef(name = "dropView", namespace = "http://www.liquibase.org/xml/ns/dbchangelog/1.9", type = DropView.class)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute
    protected String changeSetPath;
    @XmlAttribute
    protected String changeSetAuthor;
    @XmlAttribute
    protected String changeSetId;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddNotNullConstraint }
     * {@link Update }
     * {@link AddAutoIncrement }
     * {@link AddForeignKeyConstraint }
     * {@link Delete }
     * {@link CreateProcedure }
     * {@link DropPrimaryKey }
     * {@link Stop }
     * {@link DropForeignKeyConstraint }
     * {@link ModifyColumn }
     * {@link DropColumn }
     * {@link AlterSequence }
     * {@link Rollback }
     * {@link String }
     * {@link RenameView }
     * {@link DropUniqueConstraint }
     * {@link LoadData }
     * {@link DropSequence }
     * {@link RenameTable }
     * {@link AddColumn }
     * {@link MergeColumns }
     * {@link DropNotNullConstraint }
     * {@link CreateTable }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link DropDefaultValue }
     * {@link RenameColumn }
     * {@link DropTable }
     * {@link AddDefaultValue }
     * {@link CustomChange }
     * {@link AddUniqueConstraint }
     * {@link DropAllForeignKeyConstraints }
     * {@link CreateSequence }
     * {@link AddLookupTable }
     * {@link Sql }
     * {@link ExecuteCommand }
     * {@link Insert }
     * {@link CreateView }
     * {@link CreateIndex }
     * {@link AddPrimaryKey }
     * {@link DropIndex }
     * {@link SqlFile }
     * {@link DropView }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the changeSetPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeSetPath() {
        return changeSetPath;
    }

    /**
     * Sets the value of the changeSetPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeSetPath(String value) {
        this.changeSetPath = value;
    }

    /**
     * Gets the value of the changeSetAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeSetAuthor() {
        return changeSetAuthor;
    }

    /**
     * Sets the value of the changeSetAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeSetAuthor(String value) {
        this.changeSetAuthor = value;
    }

    /**
     * Gets the value of the changeSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeSetId() {
        return changeSetId;
    }

    /**
     * Sets the value of the changeSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeSetId(String value) {
        this.changeSetId = value;
    }

}
